version: '2'
services:
  hadoop_onbuild:
    image: 'vietanh85/hadoop-onbuild:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.onbuild

  hdfs_master:
    image: 'vietanh85/hdfs:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.hdfs
    depends_on:
    - hadoop_onbuild
