version: '2'
services:
  hadoop_onbuild:
    image: 'vietanh85/hadoop-onbuild:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.onbuild

  hdfs_name:
    image: 'vietanh85/hdfs-name:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.hdfs.name
    depends_on:
    - hadoop_onbuild

  hdfs_data:
    image: 'vietanh85/hdfs-data:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.hdfs.data
    depends_on:
    - hadoop_onbuild
