FROM vietanh85/hadoop-onbuild:2.7.1

ADD bin/bootstrap.hdfs.name.sh $HADOOP_HOME/bin/bootstrap.sh
RUN chown root:root $HADOOP_HOME/bin/bootstrap.sh && chmod 700 $HADOOP_HOME/bin/bootstrap.sh

RUN rm $HADOOP_CONF_DIR/yarn-site.xml && rm $HADOOP_CONF_DIR/mapred-site.xml

CMD [ "supervisord" ]