version: '2'
services:
  hadoop-onbuild:
    image: 'vietanh85/hadoop-onbuild:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.onbuild

  hdfs-master:
    image: 'vietanh85/hdfs:2.7.1'
    build: 
      context: '.'
      dockerfile: Dockerfile.hdfs
    ports:
    - '50010:50010'
    - '50020:50020'
    - '50070:50070'
    - '50075:50075'
    - '50090:50090'
    - '9000:9000'
    depends_on:
    - hadoop-onbuild
