FROM vietanh85/hadoop-onbuild:2.7.1

ADD bin/bootstrap.yarn.sh $HADOOP_HOME/bin/bootstrap.sh
RUN chown root:root $HADOOP_HOME/bin/bootstrap.sh && chmod 700 $HADOOP_HOME/bin/bootstrap.sh

# no need these files for yarn
RUN rm $HADOOP_CONF_DIR/core-site.xml && rm $HADOOP_CONF_DIR/hdfs-site.xml

CMD [ "supervisord" ]